### ISSUE TITLE
Problematic ANSI artwork

### ISSUE THREAD

**Issue by jcubic** [netzkolchose/node-ansiparser#1]
I have problematic ANSI artwork, issue reported in jcubic/jquery.terminal#622
Do you have any testing code that show that your library is working fine? I will debug on my end but if you have any testing code that test ANSI escape you can check if it renders properly.

in Xterm it's not exactly as on the screen https://codepen.io/jcubic/pen/abNYqzE but it looks similar to XFce terminal that I'm using.

**Comment by jerch** [comment]
> Do you have any testing code that show that your library is working fine?

Well the parser is tested against all definitions (states and its transitions) of the DEC parser given on VT100.net. You can find the tests under `/test/test.js`. In terms of defined aspects of the Vt100 parser the tests have roughly 100% coverage.

Still some input might fail for other reasons:
- the input was not made for DEC compatible VTs, thus dont follow the DEC sequences
- the input is derived from latin-1 encoding and contains 8bit C1 codes, those will break if not properly decoded beforehand (JS typically assumes UTF-8 encoding for most default string actions)

Ofc there is a small chance of errors in the parser. Do you have the original data of that artwork somewhere?

**Comment by jcubic** [comment]
The original file can be found at https://16colo.rs/pack/impure77/xz-tce.ans (this is html page with link to file) I have copy at my terminal website because it have corse enabled so I can test on codepen.

**Comment by jerch** [comment]
@jcubic 

According to the wikipedia article ANSI arts are 8bit using codepage 437, and may contain special ANSI.SYS sequences. I see here 2 possible problems:
- You will need a proper escape sequence aware converter from 8bit CP-437 to UTF-8. This cannot easily be done by general purpose converters like `iconv`, as they might scramble escape sequences.
- custom ANSI.SYS sequences need to be translated into DEC compatible sequences

To get this correctly working you would need a converter, that understands 8bit CP-437 input with these custom sequences (kinda a full ANSI.SYS parser), then can replace the string parts with correct Unicode codepoints mapped from CP-437 and finds analogous sequences for any non DEC compatible escape sequence. Furthermore that converter would have to be aware of typical behavior pattern of the original DOS console target like EOL wrapping, screen sizes etc and inject additional terminal sequences to deal with that. To make it short - such a converter would be a two-sided terminal emulator - input side emulates a DOS console, and the output side being aware of DEC VT emulation. 

The closest we have in that regard is `luit`, which can at least do the correct encoding/charmap replacements. Not sure, if it understands/translates the ANSI.SYS sequences or respects DOS console behavior in general. Since it originates as a tool from the unix world to level out encoding differences, DOS console behavior might not be implemented there.

Are those examples meant to work correctly on older DOS boxes?

**Comment by jcubic** [comment]
I have no idea how those images are generated, I've just assumed that the output should be the same with ANSI parser as on the preview. What about if I run the parser first on CP-437 and in print from the parser I do iconv conversion, will that work?

**Comment by jerch** [comment]
> What about if I run the parser first on CP-437 and in print from the parser I do iconv conversion, will that work?

That might work, but you will have to check first, which control codes are actually supported by DOS console. Esp. C1 positions (`0x80 .. 0x9F`) might not be supported. If thats the case, you'd need to extend `inst_x` with print rules for those unsupported controls.

To sum this up, it might work this way:
- first convert byte values directly to bytestring keeping the value (e.g. `0x00` --> `'\x00'`, ..., `0xFF` --> `'\xFF'`)
- feed that to the parser
- parser will create a series of `inst_p, inst_x, inst_c` terminal instructions (imho others should not happen for ANSI arts)
- `inst_p` now get printable chars, but still with wrong bytestring value, call `convert_printables` before printing them
- `inst_x` gets C0 and C1 controls known by the parser, unsupported controls will be caught by a patch and get rerouted to print action
- `inst_c` gets all found CSI sequences, implemented them the same way as DOS console would treat them

Here is some rough code how this might look like (without using iconv, instead relying on own charmap conversion):
```javascript
// lookup unsupported controls of DOS console and add them here with its bytestring value
const UNSUPPORTED_CONTROLS = ['\x80', '\x81', ...];

// charmap for CP437 (can be found on wikipedia)
CP437 = ['\x00', ...,'\xA0'];

function convert_printables(s) {
  let result = '';
  for (let i = 0; i < s.length; ++i) result += CP437[s.charCodeAt(i)];
  return result;
}

function inst_p(s) {
  s_converted = convert_printables(s);
  // do your normal print actions here
  ...
}

function inst_x(flag) {
  if (flag in UNSUPPORTED_CONTROLS) {
    inst_p(flag);  // flag gets treated as printable
  }
  switch (flag) {
    ...
  }
}

function inst_c(...) {
  // implement all needed sequences here
  ...
}
```

Edit: I assumed above that unsupported controls in DOS console would always end up as being printed. If thats not the case (a flag does literally nothing), just dont add it to the `UNSUPPORTED_CONTROLS` array and leave that flag unimplemented in `switch ...` in `inst_x`.

**Comment by jcubic** [comment]
Thanks for the explanation, I think that I will leave it for now, but I will get back when I find some time. It would be nice to not need iconv for CP437 images since this is the only encoding that I want to support.

**Comment by jerch** [comment]
@jcubic Yes I think iconv as dependency is way too heavy for such a small task. You can easily implement CP437 to Unicode yourself (see above).

**Comment by jerch** [comment]
@jcubic Had another look at the earth example. It seems to be created on Amiga, thus DOS console might not apply at all. You gonna have to find out, which codepage/encoding amiga typically used. Furthermore the font used is "Topaz" which has different glyphs at certain positions than normally.

Taking both into account I fiddled around abit and got this far:

![grafik](https://user-images.githubusercontent.com/6193135/92997416-712a4200-f513-11ea-85a4-fdf8434e0bd9.png)

This looks much closer to the original than everything else. Note that ISO-88591-1 (latin-1) matches best in terms of chars, maybe this was the default on Amiga. As font I used [Amiga Topaz Unicode Rus](http://www.fontsaddict.com/font/amiga-topaz-unicode-rus.html), not sure how closely it resembles the original Amiga font.

There are still some offset issues in the output, mainly it misses those diagonal striped glyphs. Not sure where those where located in the byte range (but you can find them by inspecting the data).

**Comment by jcubic** [comment]
I think that if that's different OS then it's not worth  the trouble to fix. I've created bookmark that runs on 16colors page and most artworks are fine, except XBin that it's binary format and some glitches will investigate those if the are not on Amiga. Thanks for investigating and time spent on this.

**Comment by jerch** [comment]
My last trial (promised :smile_cat:):

![grafik](https://user-images.githubusercontent.com/6193135/92999840-78a61700-f524-11ea-9c5f-9d6d9525b65c.png)


Changes to xterm.js:
- DEL is a printable char on Amiga, replacing it with ░ (light shade)  fixes most offset errors (see [here](https://de.wikipedia.org/wiki/Commodore_Amiga_(Zeichensatz)))
- `0x0F` (SO) behaves weird, I replaced it with ▒ (middle shade), which fixes all remaining offset errors
- map all FG colors to bright ones

The replacements above are not quite correct, as it still shows different dotted pattern than the original. To get this perfectly matching, you'd have to lookup correct DEL and SO handling/behavior on amiga terminal, plus its color register behavior.
