### ISSUE TITLE
Weird parser issue

### ISSUE THREAD

**Issue by jcubic** [netzkolchose/node-ansiparser#2]
I have another example that don't parse properly https://16colo.rs/pack/fire-31/N-CRYPT2.ANS
I had some issues with some characters like 0x0F and 0x00 that should be star and space but this one looks like a mess, it's even worse in Linux Terminal. Do you have a time to look at this file? 

in my code on [Codepen](https://codepen.io/jcubic/pen/pxdxmN?editors=0110) I have this code (that I've added even before I used your parser):
```javascript
        // remove code that move cursor after new line - hope this works
        str = str.replace(/[\r\n]{1,2}\x1b\[A\x1b\[[0-9]+C/g, '');
```
and with this line it seems to render properly. Any clue how this should be handled with your parser?

**Comment by jcubic** [comment]
It's not an issue anymore, I've deleted that code.

**Comment by jerch** [comment]
Oh sorry - missed that issue. Glad you solved it the other way around.
