### ISSUE TITLE
Unsued code error

### ISSUE THREAD

**Issue by jcubic** [netzkolchose/node-ansiparser#5]
I've included the library in one of my projects and I've scanned it with [DeepScan](https://deepscan.io/).

It found an error in your code

```javascript
EXECUTABLES.concat(r(0x1c, 0x20));
```
This code doesn't have side effects because `concat` don't add items to the array only returns a new Array.

You need to have:

```javascript
var EXECUTABLES = r(0x00, 0x18);
EXECUTABLES.push(0x19);
EXECUTABLES = EXECUTABLES.concat(r(0x1c, 0x20));
```

**Comment by jerch** [comment]
Woops - yepp thats a bug, thx for spotting it.
